# Generated by Django 5.1.6 on 2025-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notes_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='txt',
        ),
        migrations.AddField(
            model_name='notes',
            name='check_username',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.CharField(default=None, max_length=100000),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
