# Generated by Django 5.1.6 on 2025-02-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_notes_txt_notes_check_username_notes_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
